# Generated by Django 4.2.11 on 2024-04-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_proile',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
