# Generated by Django 4.2.11 on 2024-04-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_proile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_profile',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
