# Generated by Django 4.2.11 on 2024-04-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_proile',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_profile',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
