# Generated by Django 4.2.11 on 2024-04-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
