# Generated by Django 4.2.11 on 2024-04-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_customuser_is_admin_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('institution', 'Institution'), ('student', 'Student')], max_length=20, null=True),
        ),
    ]
