# Generated by Django 4.2.11 on 2024-04-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_customuser_role_customuser_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile',
            field=models.ImageField(null=True, upload_to='user_profile'),
        ),
    ]
