# Generated by Django 4.2.11 on 2024-05-09 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_customuser_father_name_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='FORGOTOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('tp_created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otpss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
