# Generated by Django 4.2.11 on 2024-04-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
