# Generated by Django 4.2.11 on 2024-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institution', '0005_category_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='explanation',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
