# Generated by Django 4.2.11 on 2024-04-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institution', '0006_questionbank_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='questionset',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=200),
        ),
    ]
