# Generated by Django 4.2.11 on 2024-04-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institution', '0008_savequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='savequestion',
            name='time_taken_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
