# Generated by Django 4.2.11 on 2024-04-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institution', '0010_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='questions',
            new_name='question',
        ),
    ]
