# Generated by Django 4.2.11 on 2024-05-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institution', '0017_result_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='savequestion',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
