# Generated by Django 4.2.11 on 2024-05-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institution', '0018_savequestion_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savequestion',
            name='time_taken_seconds',
        ),
        migrations.AddField(
            model_name='savequestion',
            name='time_taken',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
