# Generated by Django 4.2.11 on 2024-05-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institution', '0020_examattempt_savequestion_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='current_question',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='current_question',
        ),
    ]
